services:
  - type: web
    name: arc-server
    runtime: node
    region: frankfurt
    buildCommand: npm install && npm run build && cd server && npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
